[/]
default='8a2af8cc-a024-4ca0-850d-b545e3b48ae1'
list=['8a2af8cc-a024-4ca0-850d-b545e3b48ae1']

[:0bfedda4-a707-4a77-9211-69ae23218480]
background-color='rgb(0,0,0)'
bold-color='#61afef'
bold-color-same-as-fg=false
font='MesloLGS NF 12'
foreground-color='#abb2bf'
palette=['#000000', '#e06c75', '#98c379', '#e5c07b', '#61afef', '#c678dd', '#56b6c2', '#abb2bf', '#3e4452', '#e06c75', '#98c379', '#e5c07b', '#61afef', '#c678dd', '#56b6c2', '#ffffff']
use-system-font=false
use-theme-colors=false
visible-name='drakula'

[:3f93038a-3876-4d0e-b530-627a3f225dac]
custom-command='tmux new-session -A -s default'
font='MesloLGS NF 12'
use-custom-command=true
use-system-font=false
visible-name='tmux'

[:8a2af8cc-a024-4ca0-850d-b545e3b48ae1]
background-color='rgb(0,0,0)'
bold-color='#ff4081'
font='MesloLGS NF 12'
foreground-color='#cfd8dc'
palette=['#000000', '#ff5252', '#69f0ae', '#ffab40', '#448aff', '#ff4081', '#40c4ff', '#cfd8dc', '#546e7a', '#ff8a80', '#b9f6ca', '#ffd740', '#82b1ff', '#ff80ab', '#84ffff', '#ffffff']
use-system-font=false
use-theme-colors=false
visible-name='我的最爱'
